// This enum is autogenerated, do not modify (EnumFileBuilder.cs)
// Generation made on: 2/12/2018 2:11:14 AM
public static class Layer {
	// Generated with LayerEnumBuilder.cs
	public const int Default = 0;
	public const int TransparentFX = 1;
	public const int IgnoreRaycast = 2;
	public const int Water = 4;
	public const int UI = 5;
	public const int Walkable = 8;
	public const int Enemy = 9;
	public const int Object = 10;
	public const int Player = 11;
	public const int NPCs = 12;
	public const int EnemyAttack = 13;
	public const int AllyAttack = 14;
	public const int Audio = 15;
}