// This enum is autogenerated, do not modify (EnumFileBuilder.cs)
// Generation made on: 2/5/2018 10:48:00 PM
public enum Layer {
	// Generated with LayerEnumBuilder.cs
	Default = 0,
	TransparentFX = 1,
	IgnoreRaycast = 2,
	Water = 4,
	UI = 5,
	Walkable = 8,
	Enemy = 9,
	Object = 10,
	Player = 11,
	NPCs = 12,
	EnemyAttack = 13,
	AllyAttack = 14,
	Audio = 15,
}